[package]
name = "kuterm"
version = "0.0.7"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "highly configurable, gpu accelerated terminal"
repository = "https://github.com/roworu/kuterm"
authors = ["roworu"]
publish = false

[package.metadata.deb]
section = "utils"
assets = [
    ["target/release/kuterm", "usr/bin/", "755"],
    ["assets/kuterm.desktop", "usr/share/applications/", "644"],
    ["assets/logo/icon_256.png", "usr/share/icons/hicolor/256x256/apps/kuterm.png", "644"],
]

[package.metadata.generate-rpm]
assets = [
    { source = "target/release/kuterm", dest = "/usr/bin/kuterm", mode = "755" },
    { source = "assets/kuterm.desktop", dest = "/usr/share/applications/kuterm.desktop", mode = "644" },
    { source = "assets/logo/icon_256.png", dest = "/usr/share/icons/hicolor/256x256/apps/kuterm.png", mode = "644" },
]

[dependencies]
gpui = { git = "https://github.com/zed-industries/zed", rev = "cd8c4674188613e32c219ace84a5cd62f5d8f708" }
gpui_platform = { git = "https://github.com/zed-industries/zed", rev = "cd8c4674188613e32c219ace84a5cd62f5d8f708", features = ["wayland", "x11", "font-kit"] }
alacritty_terminal = { git = "https://github.com/zed-industries/alacritty", rev = "4c129667ce56611becdc82de6e28218c80e2e88f" }
anyhow = "1"
image = { version = "0.25", default-features = false, features = ["png"] }
futures = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json_lenient = "0.2"
skrifa = "0.47"

[dev-dependencies]
gpui = { git = "https://github.com/zed-industries/zed", rev = "cd8c4674188613e32c219ace84a5cd62f5d8f708", features = ["test-support"] }

[profile.dev.package."*"]
opt-level = 2
